syntax = "proto3";

package swe;

option go_package = "github.com/jenujari/go-swe-api/proto";

service EphService {
  rpc Ping(PingRequest) returns (PingResponse);
  rpc GetPos(PosRequest) returns (PosResponse);
  rpc FindConjunction(ConjunctionRequest) returns (ConjunctionResponse);
  rpc Tithy(TithyRequest) returns (TithyResponse);
  rpc GetBalas(BalasRequest) returns (BalasResponse);
}

message PingRequest {}

message PingResponse {
  string status    = 1;
  string timestamp = 2;
  string version   = 3;
}

message PosRequest {
  string time        = 1;
  string planet_name = 2;
}

message DMS {
  bool  is_negative = 1;
  int32 d           = 2;
  int32 m           = 3;
  float s           = 4;
}

message NakshatraPada {
  string name = 1;
  int32  pada = 2;
}

message PlanetCord {
  string        name           = 1;
  double        longitude      = 2;
  double        latitude       = 3;
  double        distance       = 4;
  double        speed_long     = 5;
  double        speed_lat      = 6;
  double        speed_dist     = 7;
  string        speed_category = 8;
  string        vedha          = 9;
  DMS           longitude_dms  = 10;
  DMS           latitude_dms   = 11;
  DMS           speed_long_dms = 12;
  string        sign           = 13;
  NakshatraPada nakshatra      = 14;
  bool          is_retro       = 15;
  string        sign_lord      = 16;
  string        sign_lordship  = 17;
  string        navamsa_sign   = 18;
  bool          vargottama     = 19;
  string        vedha_target   = 20;
}

message PosResponse {
  map<string, PlanetCord> results = 1;
}

message ConjunctionRequest {
  string start   = 1;
  string end     = 2;
  string planet1 = 3;
  string planet2 = 4;
  int32  orb     = 5;
  double step    = 6;
}

message ConjunctionResponse {
  string start = 1;
  string end   = 2;
}

message TithyRequest {
  string timestamp = 1;
}

message TithyResponse {
  int32 tithy = 1;
  string nakshatra = 2;
  string weekday = 3;
}

message BalasRequest {
  string timestamp = 1;
}

message PlanetBalas {
  PlanetCord cords         = 1;
  double     uday_bala     = 2;
  double     uchcha_bala   = 3;
  double     vakra_bala    = 4;
  double     kshetra_bala  = 5;
  double     navamsha_bala = 6;
}

message BalasResponse {
  map<string, PlanetBalas> results = 1;
}
