// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: swe.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_swe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_swe_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_swe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_swe_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PingResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type PosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          string                 `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	PlanetName    string                 `protobuf:"bytes,2,opt,name=planet_name,json=planetName,proto3" json:"planet_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PosRequest) Reset() {
	*x = PosRequest{}
	mi := &file_swe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PosRequest) ProtoMessage() {}

func (x *PosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PosRequest.ProtoReflect.Descriptor instead.
func (*PosRequest) Descriptor() ([]byte, []int) {
	return file_swe_proto_rawDescGZIP(), []int{2}
}

func (x *PosRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *PosRequest) GetPlanetName() string {
	if x != nil {
		return x.PlanetName
	}
	return ""
}

type DMS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsNegative    bool                   `protobuf:"varint,1,opt,name=is_negative,json=isNegative,proto3" json:"is_negative,omitempty"`
	D             int32                  `protobuf:"varint,2,opt,name=d,proto3" json:"d,omitempty"`
	M             int32                  `protobuf:"varint,3,opt,name=m,proto3" json:"m,omitempty"`
	S             float32                `protobuf:"fixed32,4,opt,name=s,proto3" json:"s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DMS) Reset() {
	*x = DMS{}
	mi := &file_swe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DMS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DMS) ProtoMessage() {}

func (x *DMS) ProtoReflect() protoreflect.Message {
	mi := &file_swe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DMS.ProtoReflect.Descriptor instead.
func (*DMS) Descriptor() ([]byte, []int) {
	return file_swe_proto_rawDescGZIP(), []int{3}
}

func (x *DMS) GetIsNegative() bool {
	if x != nil {
		return x.IsNegative
	}
	return false
}

func (x *DMS) GetD() int32 {
	if x != nil {
		return x.D
	}
	return 0
}

func (x *DMS) GetM() int32 {
	if x != nil {
		return x.M
	}
	return 0
}

func (x *DMS) GetS() float32 {
	if x != nil {
		return x.S
	}
	return 0
}

type NakshatraPada struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pada          int32                  `protobuf:"varint,2,opt,name=pada,proto3" json:"pada,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NakshatraPada) Reset() {
	*x = NakshatraPada{}
	mi := &file_swe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NakshatraPada) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NakshatraPada) ProtoMessage() {}

func (x *NakshatraPada) ProtoReflect() protoreflect.Message {
	mi := &file_swe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NakshatraPada.ProtoReflect.Descriptor instead.
func (*NakshatraPada) Descriptor() ([]byte, []int) {
	return file_swe_proto_rawDescGZIP(), []int{4}
}

func (x *NakshatraPada) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NakshatraPada) GetPada() int32 {
	if x != nil {
		return x.Pada
	}
	return 0
}

type PlanetCord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Longitude     float64                `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Distance      float64                `protobuf:"fixed64,3,opt,name=distance,proto3" json:"distance,omitempty"`
	SpeedLong     float64                `protobuf:"fixed64,4,opt,name=speed_long,json=speedLong,proto3" json:"speed_long,omitempty"`
	SpeedLat      float64                `protobuf:"fixed64,5,opt,name=speed_lat,json=speedLat,proto3" json:"speed_lat,omitempty"`
	SpeedDist     float64                `protobuf:"fixed64,6,opt,name=speed_dist,json=speedDist,proto3" json:"speed_dist,omitempty"`
	LongitudeDms  *DMS                   `protobuf:"bytes,7,opt,name=longitude_dms,json=longitudeDms,proto3" json:"longitude_dms,omitempty"`
	LatitudeDms   *DMS                   `protobuf:"bytes,8,opt,name=latitude_dms,json=latitudeDms,proto3" json:"latitude_dms,omitempty"`
	SpeedLongDms  *DMS                   `protobuf:"bytes,9,opt,name=speed_long_dms,json=speedLongDms,proto3" json:"speed_long_dms,omitempty"`
	Sign          string                 `protobuf:"bytes,10,opt,name=sign,proto3" json:"sign,omitempty"`
	Nakshatra     *NakshatraPada         `protobuf:"bytes,11,opt,name=nakshatra,proto3" json:"nakshatra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanetCord) Reset() {
	*x = PlanetCord{}
	mi := &file_swe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanetCord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanetCord) ProtoMessage() {}

func (x *PlanetCord) ProtoReflect() protoreflect.Message {
	mi := &file_swe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanetCord.ProtoReflect.Descriptor instead.
func (*PlanetCord) Descriptor() ([]byte, []int) {
	return file_swe_proto_rawDescGZIP(), []int{5}
}

func (x *PlanetCord) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *PlanetCord) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *PlanetCord) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *PlanetCord) GetSpeedLong() float64 {
	if x != nil {
		return x.SpeedLong
	}
	return 0
}

func (x *PlanetCord) GetSpeedLat() float64 {
	if x != nil {
		return x.SpeedLat
	}
	return 0
}

func (x *PlanetCord) GetSpeedDist() float64 {
	if x != nil {
		return x.SpeedDist
	}
	return 0
}

func (x *PlanetCord) GetLongitudeDms() *DMS {
	if x != nil {
		return x.LongitudeDms
	}
	return nil
}

func (x *PlanetCord) GetLatitudeDms() *DMS {
	if x != nil {
		return x.LatitudeDms
	}
	return nil
}

func (x *PlanetCord) GetSpeedLongDms() *DMS {
	if x != nil {
		return x.SpeedLongDms
	}
	return nil
}

func (x *PlanetCord) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *PlanetCord) GetNakshatra() *NakshatraPada {
	if x != nil {
		return x.Nakshatra
	}
	return nil
}

type PosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       map[string]*PlanetCord `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PosResponse) Reset() {
	*x = PosResponse{}
	mi := &file_swe_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PosResponse) ProtoMessage() {}

func (x *PosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swe_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PosResponse.ProtoReflect.Descriptor instead.
func (*PosResponse) Descriptor() ([]byte, []int) {
	return file_swe_proto_rawDescGZIP(), []int{6}
}

func (x *PosResponse) GetResults() map[string]*PlanetCord {
	if x != nil {
		return x.Results
	}
	return nil
}

type ConjunctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         string                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Planet1       string                 `protobuf:"bytes,3,opt,name=planet1,proto3" json:"planet1,omitempty"`
	Planet2       string                 `protobuf:"bytes,4,opt,name=planet2,proto3" json:"planet2,omitempty"`
	Orb           int32                  `protobuf:"varint,5,opt,name=orb,proto3" json:"orb,omitempty"`
	Step          float64                `protobuf:"fixed64,6,opt,name=step,proto3" json:"step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConjunctionRequest) Reset() {
	*x = ConjunctionRequest{}
	mi := &file_swe_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConjunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConjunctionRequest) ProtoMessage() {}

func (x *ConjunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swe_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConjunctionRequest.ProtoReflect.Descriptor instead.
func (*ConjunctionRequest) Descriptor() ([]byte, []int) {
	return file_swe_proto_rawDescGZIP(), []int{7}
}

func (x *ConjunctionRequest) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *ConjunctionRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *ConjunctionRequest) GetPlanet1() string {
	if x != nil {
		return x.Planet1
	}
	return ""
}

func (x *ConjunctionRequest) GetPlanet2() string {
	if x != nil {
		return x.Planet2
	}
	return ""
}

func (x *ConjunctionRequest) GetOrb() int32 {
	if x != nil {
		return x.Orb
	}
	return 0
}

func (x *ConjunctionRequest) GetStep() float64 {
	if x != nil {
		return x.Step
	}
	return 0
}

type ConjunctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         string                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConjunctionResponse) Reset() {
	*x = ConjunctionResponse{}
	mi := &file_swe_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConjunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConjunctionResponse) ProtoMessage() {}

func (x *ConjunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swe_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConjunctionResponse.ProtoReflect.Descriptor instead.
func (*ConjunctionResponse) Descriptor() ([]byte, []int) {
	return file_swe_proto_rawDescGZIP(), []int{8}
}

func (x *ConjunctionResponse) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *ConjunctionResponse) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

var File_swe_proto protoreflect.FileDescriptor

const file_swe_proto_rawDesc = "" +
	"\n" +
	"\tswe.proto\x12\x03swe\"\r\n" +
	"\vPingRequest\"^\n" +
	"\fPingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"A\n" +
	"\n" +
	"PosRequest\x12\x12\n" +
	"\x04time\x18\x01 \x01(\tR\x04time\x12\x1f\n" +
	"\vplanet_name\x18\x02 \x01(\tR\n" +
	"planetName\"P\n" +
	"\x03DMS\x12\x1f\n" +
	"\vis_negative\x18\x01 \x01(\bR\n" +
	"isNegative\x12\f\n" +
	"\x01d\x18\x02 \x01(\x05R\x01d\x12\f\n" +
	"\x01m\x18\x03 \x01(\x05R\x01m\x12\f\n" +
	"\x01s\x18\x04 \x01(\x02R\x01s\"7\n" +
	"\rNakshatraPada\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04pada\x18\x02 \x01(\x05R\x04pada\"\x8f\x03\n" +
	"\n" +
	"PlanetCord\x12\x1c\n" +
	"\tlongitude\x18\x01 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1a\n" +
	"\bdistance\x18\x03 \x01(\x01R\bdistance\x12\x1d\n" +
	"\n" +
	"speed_long\x18\x04 \x01(\x01R\tspeedLong\x12\x1b\n" +
	"\tspeed_lat\x18\x05 \x01(\x01R\bspeedLat\x12\x1d\n" +
	"\n" +
	"speed_dist\x18\x06 \x01(\x01R\tspeedDist\x12-\n" +
	"\rlongitude_dms\x18\a \x01(\v2\b.swe.DMSR\flongitudeDms\x12+\n" +
	"\flatitude_dms\x18\b \x01(\v2\b.swe.DMSR\vlatitudeDms\x12.\n" +
	"\x0espeed_long_dms\x18\t \x01(\v2\b.swe.DMSR\fspeedLongDms\x12\x12\n" +
	"\x04sign\x18\n" +
	" \x01(\tR\x04sign\x120\n" +
	"\tnakshatra\x18\v \x01(\v2\x12.swe.NakshatraPadaR\tnakshatra\"\x93\x01\n" +
	"\vPosResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.swe.PosResponse.ResultsEntryR\aresults\x1aK\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.swe.PlanetCordR\x05value:\x028\x01\"\x96\x01\n" +
	"\x12ConjunctionRequest\x12\x14\n" +
	"\x05start\x18\x01 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\tR\x03end\x12\x18\n" +
	"\aplanet1\x18\x03 \x01(\tR\aplanet1\x12\x18\n" +
	"\aplanet2\x18\x04 \x01(\tR\aplanet2\x12\x10\n" +
	"\x03orb\x18\x05 \x01(\x05R\x03orb\x12\x12\n" +
	"\x04step\x18\x06 \x01(\x01R\x04step\"=\n" +
	"\x13ConjunctionResponse\x12\x14\n" +
	"\x05start\x18\x01 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\tR\x03end2\xac\x01\n" +
	"\n" +
	"SWEService\x12+\n" +
	"\x04Ping\x12\x10.swe.PingRequest\x1a\x11.swe.PingResponse\x12+\n" +
	"\x06GetPos\x12\x0f.swe.PosRequest\x1a\x10.swe.PosResponse\x12D\n" +
	"\x0fFindConjunction\x12\x17.swe.ConjunctionRequest\x1a\x18.swe.ConjunctionResponseBe\n" +
	"\acom.sweB\bSweProtoP\x01Z$github.com/jenujari/go-swe-api/proto\xa2\x02\x03SXX\xaa\x02\x03Swe\xca\x02\x03Swe\xe2\x02\x0fSwe\\GPBMetadata\xea\x02\x03Sweb\x06proto3"

var (
	file_swe_proto_rawDescOnce sync.Once
	file_swe_proto_rawDescData []byte
)

func file_swe_proto_rawDescGZIP() []byte {
	file_swe_proto_rawDescOnce.Do(func() {
		file_swe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swe_proto_rawDesc), len(file_swe_proto_rawDesc)))
	})
	return file_swe_proto_rawDescData
}

var file_swe_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_swe_proto_goTypes = []any{
	(*PingRequest)(nil),         // 0: swe.PingRequest
	(*PingResponse)(nil),        // 1: swe.PingResponse
	(*PosRequest)(nil),          // 2: swe.PosRequest
	(*DMS)(nil),                 // 3: swe.DMS
	(*NakshatraPada)(nil),       // 4: swe.NakshatraPada
	(*PlanetCord)(nil),          // 5: swe.PlanetCord
	(*PosResponse)(nil),         // 6: swe.PosResponse
	(*ConjunctionRequest)(nil),  // 7: swe.ConjunctionRequest
	(*ConjunctionResponse)(nil), // 8: swe.ConjunctionResponse
	nil,                         // 9: swe.PosResponse.ResultsEntry
}
var file_swe_proto_depIdxs = []int32{
	3, // 0: swe.PlanetCord.longitude_dms:type_name -> swe.DMS
	3, // 1: swe.PlanetCord.latitude_dms:type_name -> swe.DMS
	3, // 2: swe.PlanetCord.speed_long_dms:type_name -> swe.DMS
	4, // 3: swe.PlanetCord.nakshatra:type_name -> swe.NakshatraPada
	9, // 4: swe.PosResponse.results:type_name -> swe.PosResponse.ResultsEntry
	5, // 5: swe.PosResponse.ResultsEntry.value:type_name -> swe.PlanetCord
	0, // 6: swe.SWEService.Ping:input_type -> swe.PingRequest
	2, // 7: swe.SWEService.GetPos:input_type -> swe.PosRequest
	7, // 8: swe.SWEService.FindConjunction:input_type -> swe.ConjunctionRequest
	1, // 9: swe.SWEService.Ping:output_type -> swe.PingResponse
	6, // 10: swe.SWEService.GetPos:output_type -> swe.PosResponse
	8, // 11: swe.SWEService.FindConjunction:output_type -> swe.ConjunctionResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_swe_proto_init() }
func file_swe_proto_init() {
	if File_swe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swe_proto_rawDesc), len(file_swe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swe_proto_goTypes,
		DependencyIndexes: file_swe_proto_depIdxs,
		MessageInfos:      file_swe_proto_msgTypes,
	}.Build()
	File_swe_proto = out.File
	file_swe_proto_goTypes = nil
	file_swe_proto_depIdxs = nil
}
