// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: swe.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EphService_Ping_FullMethodName            = "/swe.EphService/Ping"
	EphService_GetPos_FullMethodName          = "/swe.EphService/GetPos"
	EphService_FindConjunction_FullMethodName = "/swe.EphService/FindConjunction"
)

// EphServiceClient is the client API for EphService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EphServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	GetPos(ctx context.Context, in *PosRequest, opts ...grpc.CallOption) (*PosResponse, error)
	FindConjunction(ctx context.Context, in *ConjunctionRequest, opts ...grpc.CallOption) (*ConjunctionResponse, error)
}

type ephServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEphServiceClient(cc grpc.ClientConnInterface) EphServiceClient {
	return &ephServiceClient{cc}
}

func (c *ephServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, EphService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ephServiceClient) GetPos(ctx context.Context, in *PosRequest, opts ...grpc.CallOption) (*PosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PosResponse)
	err := c.cc.Invoke(ctx, EphService_GetPos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ephServiceClient) FindConjunction(ctx context.Context, in *ConjunctionRequest, opts ...grpc.CallOption) (*ConjunctionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConjunctionResponse)
	err := c.cc.Invoke(ctx, EphService_FindConjunction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EphServiceServer is the server API for EphService service.
// All implementations must embed UnimplementedEphServiceServer
// for forward compatibility.
type EphServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	GetPos(context.Context, *PosRequest) (*PosResponse, error)
	FindConjunction(context.Context, *ConjunctionRequest) (*ConjunctionResponse, error)
	mustEmbedUnimplementedEphServiceServer()
}

// UnimplementedEphServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEphServiceServer struct{}

func (UnimplementedEphServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedEphServiceServer) GetPos(context.Context, *PosRequest) (*PosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPos not implemented")
}
func (UnimplementedEphServiceServer) FindConjunction(context.Context, *ConjunctionRequest) (*ConjunctionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindConjunction not implemented")
}
func (UnimplementedEphServiceServer) mustEmbedUnimplementedEphServiceServer() {}
func (UnimplementedEphServiceServer) testEmbeddedByValue()                    {}

// UnsafeEphServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EphServiceServer will
// result in compilation errors.
type UnsafeEphServiceServer interface {
	mustEmbedUnimplementedEphServiceServer()
}

func RegisterEphServiceServer(s grpc.ServiceRegistrar, srv EphServiceServer) {
	// If the following call panics, it indicates UnimplementedEphServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EphService_ServiceDesc, srv)
}

func _EphService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EphServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EphService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EphServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EphService_GetPos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EphServiceServer).GetPos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EphService_GetPos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EphServiceServer).GetPos(ctx, req.(*PosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EphService_FindConjunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConjunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EphServiceServer).FindConjunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EphService_FindConjunction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EphServiceServer).FindConjunction(ctx, req.(*ConjunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EphService_ServiceDesc is the grpc.ServiceDesc for EphService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EphService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swe.EphService",
	HandlerType: (*EphServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _EphService_Ping_Handler,
		},
		{
			MethodName: "GetPos",
			Handler:    _EphService_GetPos_Handler,
		},
		{
			MethodName: "FindConjunction",
			Handler:    _EphService_FindConjunction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "swe.proto",
}
