// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: swe.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SWEService_Ping_FullMethodName            = "/swe.SWEService/Ping"
	SWEService_GetPos_FullMethodName          = "/swe.SWEService/GetPos"
	SWEService_FindConjunction_FullMethodName = "/swe.SWEService/FindConjunction"
)

// SWEServiceClient is the client API for SWEService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SWEServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	GetPos(ctx context.Context, in *PosRequest, opts ...grpc.CallOption) (*PosResponse, error)
	FindConjunction(ctx context.Context, in *ConjunctionRequest, opts ...grpc.CallOption) (*ConjunctionResponse, error)
}

type sWEServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSWEServiceClient(cc grpc.ClientConnInterface) SWEServiceClient {
	return &sWEServiceClient{cc}
}

func (c *sWEServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, SWEService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sWEServiceClient) GetPos(ctx context.Context, in *PosRequest, opts ...grpc.CallOption) (*PosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PosResponse)
	err := c.cc.Invoke(ctx, SWEService_GetPos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sWEServiceClient) FindConjunction(ctx context.Context, in *ConjunctionRequest, opts ...grpc.CallOption) (*ConjunctionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConjunctionResponse)
	err := c.cc.Invoke(ctx, SWEService_FindConjunction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SWEServiceServer is the server API for SWEService service.
// All implementations must embed UnimplementedSWEServiceServer
// for forward compatibility.
type SWEServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	GetPos(context.Context, *PosRequest) (*PosResponse, error)
	FindConjunction(context.Context, *ConjunctionRequest) (*ConjunctionResponse, error)
	mustEmbedUnimplementedSWEServiceServer()
}

// UnimplementedSWEServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSWEServiceServer struct{}

func (UnimplementedSWEServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSWEServiceServer) GetPos(context.Context, *PosRequest) (*PosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPos not implemented")
}
func (UnimplementedSWEServiceServer) FindConjunction(context.Context, *ConjunctionRequest) (*ConjunctionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindConjunction not implemented")
}
func (UnimplementedSWEServiceServer) mustEmbedUnimplementedSWEServiceServer() {}
func (UnimplementedSWEServiceServer) testEmbeddedByValue()                    {}

// UnsafeSWEServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SWEServiceServer will
// result in compilation errors.
type UnsafeSWEServiceServer interface {
	mustEmbedUnimplementedSWEServiceServer()
}

func RegisterSWEServiceServer(s grpc.ServiceRegistrar, srv SWEServiceServer) {
	// If the following call panics, it indicates UnimplementedSWEServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SWEService_ServiceDesc, srv)
}

func _SWEService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SWEServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SWEService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SWEServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SWEService_GetPos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SWEServiceServer).GetPos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SWEService_GetPos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SWEServiceServer).GetPos(ctx, req.(*PosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SWEService_FindConjunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConjunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SWEServiceServer).FindConjunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SWEService_FindConjunction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SWEServiceServer).FindConjunction(ctx, req.(*ConjunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SWEService_ServiceDesc is the grpc.ServiceDesc for SWEService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SWEService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swe.SWEService",
	HandlerType: (*SWEServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _SWEService_Ping_Handler,
		},
		{
			MethodName: "GetPos",
			Handler:    _SWEService_GetPos_Handler,
		},
		{
			MethodName: "FindConjunction",
			Handler:    _SWEService_FindConjunction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "swe.proto",
}
