# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test with docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install build essentials
      run: sudo apt-get install -y build-essential

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.6'

    - name: start docker
      run: sudo systemctl start docker

    - name: prepare build
      run: |
        git reset --hard
        git clean -fd
        docker run --rm -v .:/workspace -w /workspace docker.io/bufbuild/buf generate proto
        docker compose -f compose.yaml build test_sweapi
        
    - name: Run golangci-lint
      run: docker compose -f compose.yaml run --entrypoint sh --rm test_sweapi -c "go tool golangci-lint run -v"

    - name: Run tests with coverage
      run: |
        docker compose -f compose.yaml run --entrypoint sh --rm test_sweapi -c "go test ./... -v -coverpkg=./... -coverprofile=coverage.out && grep -v '\\.pb\\.go' coverage.out > cov.tmp && mv cov.tmp coverage.out && go tool cover -func=coverage.out | tee coverage-summary.txt"

    - name: Generate Job Summary
      run: |
        echo "### Test Coverage Summary" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        cat coverage-summary.txt >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY

    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.out
